# Generated by Django 5.2 on 2025-04-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='webseite',
            new_name='website',
        ),
    ]
