# Generated by Django 5.2 on 2025-05-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_webseite_customuser_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
