# Generated by Django 5.2 on 2025-05-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
