# Generated by Django 5.2 on 2025-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_friendship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
