# Generated by Django 5.2 on 2025-04-15 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CONCERT', 'Concert'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('CONFERENCE', 'Conference'), ('MEETUP', 'Meetup')], max_length=15)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.TextField()),
                ('organizer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('organizer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('is_free', models.BooleanField(default=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
