# Generated by Django 5.1.7 on 2025-05-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_description_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
